version: '3'
name: neat
services:
  neat:
    image: cognite/neat:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    networks:
      - neat-net

networks:
  neat-net:
    driver: bridge
    external: false
