version: '3'
name: neat
services:
  neat:
    platform: linux/amd64
    image: ghcr.io/aker-information-model/neat:0.12.4
    ports:
      - "8000:8000"
    volumes:
      - neat-volume:/app/data
    networks:
      - neat-net

networks:
  neat-net:
    driver: bridge
    external: false

volumes:
  neat-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/data
