configs:
-   group: source_rdf_store
    label: null
    name: source_rdf_store.type
    options: null
    required: false
    type: null
    value: graphdb
description: null
groups:
-   description: null
    id: github2github
    label: Generation of data model(s) from sheets in github
    transition_to: null
    ui_config:
        pos_x: 171
        pos_y: 6


implementation_module: null
name: github2github
steps:
-   description: null
    enabled: true
    group_id: null
    id: step_trigger
    label: HTTP trigger
    method: null
    params: {}
    stype: http_trigger
    transition_to:
    - clone_github_repos
    trigger: true
    ui_config:
        pos_x: 340
        pos_y: 44

-   description: null
    enabled: true
    group_id: null
    id: clone_github_repos
    label: Clone Github repository containing sheet and GraphQL data model representations
    method: null
    params: {}
    stype: pystep
    transition_to:
    - process_sheets
    trigger: false
    ui_config:
        pos_x: 340
        pos_y: 144

-   description: null
    enabled: true
    group_id: null
    id: process_sheets
    label: Process data model sheets
    method: null
    params: {}
    stype: pystep
    transition_to:
    - update_graphql_data_model_repository
    trigger: false
    ui_config:
        pos_x: 340
        pos_y: 300

-   description: null
    enabled: true
    group_id: null
    id: update_graphql_data_model_repository
    label: Update Github repository containing GraphQL data models
    method: null
    params: {}
    stype: pystep
    transition_to:
    - sync_local_copies
    trigger: false
    ui_config:
        pos_x: 340
        pos_y: 448


-   description: null
    enabled: true
    group_id: null
    id: sync_local_copies
    label: Sync local copies of data model representations
    method: null
    params: null
    stype: pystep
    transition_to:
    - cleanup
    trigger: false
    ui_config:
        pos_x: 340
        pos_y: 600

-   description: null
    enabled: true
    group_id: null
    id: cleanup
    label: Cleanup
    method: null
    params: null
    stype: pystep
    transition_to: []
    trigger: false
    ui_config:
        pos_x: 340
        pos_y: 750