name: neat-docker
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-publish-neat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Publish Image
        run: |
               docker build -t ghcr.io/aker-information-model/neat:${{ github.ref_name }} -t ghcr.io/aker-information-model/neat:latest --build-arg source_prv_key="${{secrets.SOURCE_PRV_KEY}}" --build-arg source_pub_key="${{secrets.SOURCE_PUB_KEY}}" --build-arg output_prv_key="${{secrets.OUTPUT_PRV_KEY}}" --build-arg output_pub_key="${{secrets.OUTPUT_PUB_KEY}}" .
               docker push ghcr.io/aker-information-model/neat:${{ github.ref_name }}
               docker push ghcr.io/aker-information-model/neat:latest
